import type { Product } from '@/lib/site'

const trayMaterial = [{ label: 'Material options', value: 'Steel / aluminum alloy / stainless steel (series-dependent)' }]
const projectNote = 'Dimensions, finish and configuration are confirmed against project drawings and load requirements.'

export const catalogProducts: Product[] = [
  {
    slug: 'ladder-cable-tray', category: 'Cable Tray Systems', subcategory: 'Cable Tray',
    name: 'Ladder-Type Cable Tray', short: 'XQJ-T ladder cable support for power and large-diameter cables',
    description: 'A lightweight, ventilated cable-support system designed for power, high-voltage and low-voltage cable routing. The catalog includes straight sections, horizontal bends, tees and matching fittings.',
    image: '/catalog/products/ladder-cable-tray.webp', gallery: ['/catalog/products/ladder-cable-tray.webp'], sourcePages: [25, 26],
    highlights: ['Open ladder structure supports ventilation and heat dissipation', 'Straight sections, bends, tees and project fittings', projectNote],
    specs: [...trayMaterial, { label: 'Representative models', value: 'XQJ-T-01 / T-02 / T-03' }, { label: 'Catalog span', value: 'Typically 2,000 mm straight sections' }],
  },
  {
    slug: 'trough-cable-tray', category: 'Cable Tray Systems', subcategory: 'Cable Tray',
    name: 'Trough/Channel-Type Cable Tray', short: 'XQJ-C enclosed routing for control and sensitive-system cables',
    description: 'A fully enclosed cable-support system for computer, communication, thermocouple and control cables, particularly where shielding and environmental protection are required.',
    image: '/catalog/products/trough-cable-tray.webp', gallery: ['/catalog/products/trough-cable-tray.webp'], sourcePages: [29, 30, 31, 32, 33],
    highlights: ['Enclosed structure for protected cable routing', 'Suitable for control and communication cables', projectNote],
    specs: [...trayMaterial, { label: 'Representative models', value: 'XQJ-C-01A / C-02A / C-03A' }, { label: 'Catalog size range', value: '50 × 25 mm to 800 × 200 mm' }],
  },
  {
    slug: 'perforated-cable-tray', category: 'Cable Tray Systems', subcategory: 'Cable Tray',
    name: 'Perforated Cable Tray', short: 'XQJ-P ventilated tray for general industrial cable routing',
    description: 'Perforated tray sections combine cable support with ventilation and are supplied with matching horizontal bends, tees and connection pieces.',
    image: '/catalog/products/perforated-cable-tray.webp', gallery: ['/catalog/products/perforated-cable-tray.webp'], sourcePages: [27, 28],
    highlights: ['Ventilated perforated base', 'Straight, bend and tee configurations', projectNote],
    specs: [...trayMaterial, { label: 'Representative models', value: 'XQJ-P-01 / P-02 / P-03' }, { label: 'Catalog widths', value: '200–800 mm' }],
  },
  {
    slug: 'long-span-cable-tray', category: 'Cable Tray Systems', subcategory: 'Special Cable Support',
    name: 'Long-Span Cable Tray', short: 'DJ series cable tray for support spacing up to 6 m',
    description: 'Long-span ladder, channel and tray structures are designed for wider support spacing. The catalog provides A and B structural variants and accepts project-specific spans beyond the standard range.',
    image: '/catalog/products/long-span-cable-tray.webp', gallery: ['/catalog/products/long-span-cable-tray.webp'], sourcePages: [34, 35],
    highlights: ['Ladder, channel and perforated structural variants', 'Standard catalog support span up to 6 m', projectNote],
    specs: [...trayMaterial, { label: 'Representative series', value: 'DJ-T-A / DJ-T-B / DJ-P-A' }, { label: 'Catalog length', value: '6,000 mm' }],
  },
  {
    slug: 'cable-shaft', category: 'Cable Tray Systems', subcategory: 'Special Cable Support',
    name: 'Cable Shaft', short: 'Vertical cable-routing shaft and floor-transition assemblies',
    description: 'A modular vertical cable-shaft system with enclosure panels, frames, supports and cable outlets for building risers and floor transitions.',
    image: '/catalog/products/cable-shaft.webp', gallery: ['/catalog/products/cable-shaft.webp'], sourcePages: [36, 37],
    highlights: ['Vertical cable organization for building risers', 'Modular panels, supports and access doors', projectNote],
    specs: [{ label: 'Representative models', value: 'XQJ-DSJ series' }, { label: 'Configuration', value: '7-level / 12-level and project variants' }],
  },
  {
    slug: 'cable-tray-fittings', category: 'Cable Tray Systems', subcategory: 'Accessories',
    name: 'Cable Tray Fittings & Accessories', short: 'Bends, tees, crosses, reducers, covers and installation accessories',
    description: 'A coordinated range of fittings completes ladder, tray and channel layouts, including horizontal and vertical direction changes, tees, crosses, reducers, covers and mounting pieces.',
    image: '/catalog/products/cable-tray-accessories.webp', gallery: ['/catalog/products/cable-tray-accessories.webp'], sourcePages: [38, 39, 40, 41, 42, 43, 44, 45],
    highlights: ['Matched to ladder, tray and channel systems', 'Horizontal and vertical routing components', 'Model selection follows tray type and dimensions'],
    specs: [{ label: 'Product types', value: 'Bends / tees / crosses / reducers / covers / supports' }, { label: 'Compatibility', value: 'XQJ and LQJ catalog families' }],
  },
  {
    slug: 'hdcmc-t-copper-busbar', category: 'Busbar Trunking Systems', subcategory: 'Dense Busbar',
    name: 'HDCMC-T Copper Dense Busbar', short: 'Dense copper-conductor busbar with aluminum-alloy enclosure',
    description: 'A compact dense busbar system using copper conductors and an aluminum-alloy heat-dissipation enclosure for low-voltage power distribution.',
    image: '/catalog/products/hdcmc-t-copper-busbar.webp', gallery: ['/catalog/products/hdcmc-t-copper-busbar.webp'], sourcePages: [54, 55],
    highlights: ['Copper conductors', 'Compact dense structure', 'Catalog states enclosure protection up to IP66'],
    specs: [{ label: 'Series', value: 'HDCMC-T' }, { label: 'Conductor', value: 'Copper' }, { label: 'Rated current', value: '100–6,300 A (configuration-dependent)' }],
  },
  {
    slug: 'hdcmc-l-aluminum-busbar', category: 'Busbar Trunking Systems', subcategory: 'Dense Busbar',
    name: 'HDCMC-L Aluminum Dense Busbar', short: 'Dense aluminum-conductor busbar for cost-conscious distribution projects',
    description: 'A dense busbar series using aluminum conductors with a compact protective enclosure for project-specific low-voltage distribution.',
    image: '/catalog/products/hdcmc-l-aluminum-busbar.webp', gallery: ['/catalog/products/hdcmc-l-aluminum-busbar.webp'], sourcePages: [56, 57],
    highlights: ['Aluminum conductors', 'Compact enclosed structure', 'Multiple current and pole configurations'],
    specs: [{ label: 'Series', value: 'HDCMC-L' }, { label: 'Conductor', value: 'Aluminum' }, { label: 'Rated current', value: '400–4,000 A (configuration-dependent)' }],
  },
  {
    slug: 'hdkfw-high-strength-air-insulated-busbar', category: 'Busbar Trunking Systems', subcategory: 'Enclosed Busbar',
    name: 'HDKFW-2A High-Strength / Air-Insulated Busbar', short: 'Mechanically reinforced and air-insulated enclosed busbar family',
    description: 'The HDKFW-2A family combines reinforced enclosed construction with air-insulated configurations for industrial and commercial power-distribution routes.',
    image: '/catalog/products/hdkfw-high-strength-busbar.webp', gallery: ['/catalog/products/hdkfw-high-strength-busbar.webp', '/catalog/products/hdkfw-air-insulated-busbar.webp'], sourcePages: [58, 59, 60, 61],
    highlights: ['Reinforced enclosure structure', 'Air-insulated configurations', 'Tap-off distribution and project fittings'],
    specs: [{ label: 'Series', value: 'HDKFW-2A' }, { label: 'Structure', value: 'High-strength enclosed / air insulated' }, { label: 'Rated current', value: '250–6,300 A (series-dependent)' }],
  },
  {
    slug: 'hdnhmc-fire-resistant-busbar', category: 'Busbar Trunking Systems', subcategory: 'Special Busbar',
    name: 'HDNHMC Fire-Resistant Busbar', short: 'Fire-resistant busbar for emergency and critical distribution routes',
    description: 'A fire-resistant busbar system using heat-resistant insulation and a protected enclosure for circuits that require continuity during fire conditions.',
    image: '/catalog/products/hdnhmc-fire-resistant-busbar.webp', gallery: ['/catalog/products/hdnhmc-fire-resistant-busbar.webp'], sourcePages: [62],
    highlights: ['Fire-resistant construction', 'Copper conductor configurations', 'Catalog performance must be confirmed by applicable test documentation'],
    specs: [{ label: 'Series', value: 'HDNHMC' }, { label: 'Catalog fire condition', value: '960 °C / at least 90 minutes' }, { label: 'Rated current', value: '160–3,150 A' }],
  },
  {
    slug: 'hdcmc-g-high-voltage-busbar', category: 'Busbar Trunking Systems', subcategory: 'Special Busbar',
    name: 'HDCMC-G High-Voltage Busbar', short: 'Common-enclosure high-voltage busbar for engineered power routes',
    description: 'A common-enclosure high-voltage busbar system presented in the catalog for engineered distribution projects and designed against project electrical requirements.',
    image: '/catalog/products/hdcmc-g-high-voltage-busbar.webp', gallery: ['/catalog/products/hdcmc-g-high-voltage-busbar.webp'], sourcePages: [63, 64],
    highlights: ['Common-enclosure arrangement', 'Engineered high-voltage distribution', 'Configuration confirmed from project drawings'],
    specs: [{ label: 'Series', value: 'HDCMC-G' }, { label: 'Application', value: 'High-voltage common-enclosure distribution' }],
  },
  {
    slug: 'busbar-accessories', category: 'Busbar Trunking Systems', subcategory: 'Accessories',
    name: 'Busbar Fittings & Accessories', short: 'Joint packs, tap-off units, bends, transitions and installation pieces',
    description: 'A coordinated accessory range supports changes of direction, connections, tapping, termination and installation for Hengdi busbar systems.',
    image: '/catalog/products/busbar-accessories.webp', gallery: ['/catalog/products/busbar-accessories.webp', '/catalog/diagrams/busbar-installation.webp'], sourcePages: [49, 50, 51, 52, 53, 65, 66, 67, 68, 69, 70],
    highlights: ['Joint and connection components', 'Bends, offsets, tap-off and termination units', 'Installation layouts are engineered per project'],
    specs: [{ label: 'Accessory types', value: 'Joint / bend / tee / tap-off / termination / support' }, { label: 'Selection basis', value: 'Busbar series, current, pole arrangement and route' }],
  },
  {
    slug: 'xl-low-voltage-switchgear', category: 'Switchgear & Distribution', subcategory: 'Switchgear',
    name: 'XL Series Low-Voltage Switchgear', short: 'Complete low-voltage power and lighting distribution cabinet',
    description: 'The XL series is intended for industrial, commercial, service and civil-building low-voltage power or lighting distribution systems.',
    image: '/catalog/products/xl-switchgear.webp', gallery: ['/catalog/products/xl-switchgear.webp'], sourcePages: [71],
    highlights: ['Power and lighting distribution', 'Cabinet configuration selected per project', 'Industrial, commercial and civil applications'],
    specs: [{ label: 'Series', value: 'XL' }, { label: 'Frequency', value: '50 Hz' }, { label: 'Catalog voltage', value: 'Up to 600 V AC' }],
  },
  {
    slug: 'jxf-switchgear-cabinet', category: 'Switchgear & Distribution', subcategory: 'Switchgear',
    name: 'JXF Series Switchgear Cabinet', short: 'Assembled low-voltage distribution cabinet',
    description: 'A configurable assembled cabinet family for general low-voltage power distribution and equipment-control applications.',
    image: '/catalog/products/jxf-switchgear.webp', gallery: ['/catalog/products/jxf-switchgear.webp'], sourcePages: [72],
    highlights: ['Assembled cabinet construction', 'Project-specific component layout', 'General low-voltage distribution'],
    specs: [{ label: 'Series', value: 'JXF' }, { label: 'Configuration', value: 'Confirmed against project single-line diagram' }],
  },
  {
    slug: 'sdy-dual-power-distribution-box', category: 'Switchgear & Distribution', subcategory: 'Distribution Box',
    name: 'SDY Dual-Power Distribution Box', short: 'Dual-source changeover distribution for continuity-sensitive loads',
    description: 'The SDY series provides dual-power input and changeover distribution for installations requiring an alternate electrical source.',
    image: '/catalog/products/sdy-dual-power-box.webp', gallery: ['/catalog/products/sdy-dual-power-box.webp'], sourcePages: [73],
    highlights: ['Dual-source distribution arrangement', 'Automatic or specified changeover configuration', 'Designed to project load requirements'],
    specs: [{ label: 'Series', value: 'SDY' }, { label: 'Function', value: 'Dual-power changeover and distribution' }],
  },
  {
    slug: 'pz20-pz30-distribution-board', category: 'Switchgear & Distribution', subcategory: 'Distribution Board',
    name: 'PZ20 / PZ30 Distribution Board', short: 'Compact modular terminal distribution board',
    description: 'Compact modular boards for terminal power and lighting distribution in civil and light-commercial installations.',
    image: '/catalog/products/pz20-pz30-distribution-board.webp', gallery: ['/catalog/products/pz20-pz30-distribution-board.webp'], sourcePages: [74],
    highlights: ['Compact modular construction', 'Surface or flush installation options by model', 'Terminal circuit distribution'],
    specs: [{ label: 'Series', value: 'PZ20 / PZ30' }, { label: 'Application', value: 'Civil and light-commercial terminal distribution' }],
  },
]
