import type { Product } from '@/lib/site'

export const catalogProducts: Product[] = [
  {
    slug: 'cable-tray-series',
    category: 'Cable Tray Systems',
    subcategory: 'Cable Support Systems',
    name: 'Cable Tray Series',
    short: 'Ladder, tray, trough, long-span, shaft and matching accessory systems',
    description: 'Hengdi cable tray systems cover ladder, perforated tray, enclosed trough, long-span and vertical shaft applications. Matching bends, tees, crosses, reducers, covers and supports complete project routing layouts.',
    image: '/catalog/product-cards/cable-tray-series.webp',
    gallery: ['/catalog/product-cards/cable-tray-series.webp'],
    sourcePages: [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    highlights: ['Ladder, perforated tray and enclosed trough structures', 'Long-span and vertical cable-shaft systems', 'Complete routing and installation accessories', 'Dimensions and finishes are confirmed per project'],
    specs: [{ label: 'Main families', value: 'XQJ-T / XQJ-P / XQJ-C / DJ / XQJ-DSJ' }, { label: 'Representative widths', value: '50–1,200 mm, series-dependent' }, { label: 'Surface options', value: 'Galvanized / coated / stainless steel / aluminum alloy, project-dependent' }],
    families: [
      { name: 'XQJ-T Ladder Type', description: 'Open ladder cable support for power and large-diameter cable routing.', models: 'Straight sections, horizontal bends, tees and matching fittings' },
      { name: 'XQJ-P Perforated Tray Type', description: 'Ventilated perforated tray for general industrial cable routing.', models: 'Straight sections, bends, tees and matching fittings' },
      { name: 'XQJ-C Trough Type', description: 'Enclosed cable support for communication, control and sensitive-system cables.', models: 'Straight sections, horizontal bends, tees and matching fittings' },
      { name: 'Long-Span & Cable Shaft', description: 'Wider-support-spacing tray structures and vertical cable-shaft assemblies.', models: 'DJ and XQJ-DSJ catalog families' },
    ],
  },
  {
    slug: 'busbar-trunking-series',
    category: 'Busbar Trunking Systems',
    subcategory: 'Power Distribution Busway',
    name: 'Busbar Trunking Series',
    short: 'Dense, high-strength, air-insulated, fire-resistant and engineered busbar systems',
    description: 'Hengdi busbar trunking includes copper and aluminum dense systems, high-strength and air-insulated enclosed systems, fire-resistant systems and engineered high-voltage arrangements. Connection, tap-off, direction-change and installation accessories are selected with the route design.',
    image: '/catalog/product-cards/busbar-trunking-series.webp',
    gallery: ['/catalog/product-cards/busbar-trunking-series.webp'],
    sourcePages: [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
    highlights: ['Copper and aluminum conductor options', 'Dense, high-strength and air-insulated construction', 'Fire-resistant and project-engineered configurations', 'Complete joints, tap-off units, bends and installation accessories'],
    specs: [{ label: 'Main families', value: 'HDCMC / HDKFW-2A / HDNHMC / HDFMC / HDZMC' }, { label: 'Rated current', value: '16–6,300 A across catalog families; selected by series' }, { label: 'Protection', value: 'IP level depends on the selected product family' }],
    families: [
      { name: 'HDCMC Dense Busbar', description: 'Compact copper or aluminum conductor busbar with aluminum-alloy enclosure.', models: 'Copper and aluminum configurations' },
      { name: 'HDKFW-2A Enclosed Busbar', description: 'High-strength and air-insulated enclosed busbar configurations.', models: '4P / 5P and project variants' },
      { name: 'HDNHMC Fire-Resistant Busbar', description: 'Fire-resistant construction for critical distribution circuits.', models: 'Performance confirmed against applicable test documentation' },
      { name: 'Accessories & Engineered Routes', description: 'Joints, tap-off units, bends, terminations and installation layouts.', models: 'Selected by series, current, poles and route' },
    ],
  },
  {
    slug: 'xl-low-voltage-switchgear', category: 'Switchgear & Distribution', subcategory: 'XL Complete Switchgear',
    name: 'XL Low-Voltage Complete Switchgear', short: 'Complete cabinet for industrial, commercial and civil power or lighting distribution',
    description: 'The XL series is a low-voltage complete switchgear family for AC 50 Hz power and lighting distribution in industrial, commercial, service and civil-building applications.',
    image: '/catalog/product-cards/xl-low-voltage-switchgear.webp', gallery: ['/catalog/product-cards/xl-low-voltage-switchgear.webp'], sourcePages: [71],
    highlights: ['Power and lighting distribution', 'Three-phase three-wire or four-wire project configurations', 'Electrical components selected to project requirements'],
    specs: [{ label: 'Series', value: 'XL' }, { label: 'Frequency', value: '50 Hz' }, { label: 'Catalog voltage', value: 'Up to 600 V AC' }],
  },
  {
    slug: 'jxf-switchgear-cabinet', category: 'Switchgear & Distribution', subcategory: 'JXF Complete Switchgear',
    name: 'JXF Complete Switchgear', short: 'Low-voltage complete switchgear and distribution cabinet',
    description: 'The JXF series provides control and distribution for electrical equipment with overload, short-circuit and leakage protection configurations for modern building and industrial applications.',
    image: '/catalog/product-cards/jxf-switchgear-cabinet.webp', gallery: ['/catalog/product-cards/jxf-switchgear-cabinet.webp'], sourcePages: [72],
    highlights: ['Welded cabinet construction', 'Multiple enclosure and installation configurations', 'Protection level selected for the installation environment'],
    specs: [{ label: 'Series', value: 'JXF' }, { label: 'Catalog protection options', value: 'IP30 / IP40 / IP42 / IP55, configuration-dependent' }],
  },
  {
    slug: 'sdy-dual-power-distribution-box', category: 'Switchgear & Distribution', subcategory: 'SDY Distribution Box',
    name: 'SDY Dual-Power Distribution Box', short: 'Dual-source changeover distribution for continuity-sensitive loads',
    description: 'The SDY series is designed for public and commercial locations requiring an emergency or alternate power source, including malls, hospitals, high-rise buildings, airports, ports, hotels and guest facilities.',
    image: '/catalog/product-cards/sdy-dual-power-distribution-box.webp', gallery: ['/catalog/product-cards/sdy-dual-power-distribution-box.webp'], sourcePages: [73],
    highlights: ['Dual-source changeover distribution', 'Box and cabinet structures by current rating', 'Optional monitoring and alarm configurations'],
    specs: [{ label: 'Series', value: 'SDY' }, { label: 'Catalog changeover ratings', value: '63 A / 100 A / 225 A / 400 A / 630 A, 4P' }],
  },
  {
    slug: 'pz30-distribution-board', category: 'Switchgear & Distribution', subcategory: 'PZ30 Distribution Box',
    name: 'PZ30 Series Distribution Box', short: 'Compact modular terminal distribution box and board',
    description: 'The PZ20 and PZ30 catalog family provides compact terminal distribution and protection for electrical equipment in single-phase and three-phase final circuits.',
    image: '/catalog/product-cards/pz30-distribution-box.webp', gallery: ['/catalog/product-cards/pz30-distribution-box.webp'], sourcePages: [74],
    highlights: ['Compact modular terminal distribution', 'Metal, plastic and stainless-steel enclosure variants', 'Surface and flush installation variants'],
    specs: [{ label: 'Series', value: 'PZ20 / PZ30' }, { label: 'Rated voltage', value: '220 / 380 V' }, { label: 'Catalog load current', value: 'Up to 100 A' }],
  },
]
